set(DARWIN_SRC
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLAccountManager.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLAttributedExpression.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLAttributionInfo.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLBackgroundStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLCircleStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLClockDirectionFormatter.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLCompassDirectionFormatter.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLComputedShapeSource.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLCoordinateFormatter.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLDistanceFormatter.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLFeature.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLFillExtrusionStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLFillStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLForegroundStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLFoundation.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLGeometry.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLHeatmapStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLHillshadeStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLImageSource.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLLight.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLLight.mm.ejs
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLLineStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLLoggingConfiguration.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLMapCamera.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLMapSnapshotter.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLMultiPoint.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLNetworkConfiguration.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLOfflinePack.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLOfflineStorage.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLOpenGLStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLPointAnnotation.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLPointCollection.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLPolygon.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLPolyline.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLRasterDEMSource.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLRasterStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLRasterTileSource.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLReachability.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLRendererConfiguration.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLSDKMetricsManager.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLShape.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLShapeCollection.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLShapeOfflineRegion.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLShapeSource.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLSource.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLStyle.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLStyleLayer.mm.ejs
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLStyleLayerManager.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLStyleValue.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLSymbolStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLTilePyramidOfflineRegion.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLTileSource.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLTypes.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLVectorStyleLayer.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLVectorTileSource.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSArray+MGLAdditions.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSBundle+MGLAdditions.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSCoder+MGLAdditions.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSCompoundPredicate+MGLAdditions.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSDate+MGLAdditions.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSDictionary+MGLAdditions.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSExpression+MGLAdditions.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSPredicate+MGLAdditions.mm
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSString+MGLAdditions.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSURL+MGLAdditions.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSValue+MGLAdditions.m
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSValue+MGLStyleAttributeAdditions.mm
)

set(DARWIN_PUBLIC_HEADER
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLFoundation.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLComputedShapeSource.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLRasterStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSExpression+MGLAdditions.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLAttributedExpression.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLAnnotation.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLHillshadeStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLMapSnapshotter.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLCircleStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLAttributionInfo.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLFillExtrusionStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLOfflineStorage.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLStyleValue.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLSDKMetricsManager.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLMultiPoint.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLShapeCollection.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLPointAnnotation.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLOfflinePack.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLLoggingConfiguration.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSPredicate+MGLAdditions.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLVectorTileSource.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLRasterDEMSource.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLTypes.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLBackgroundStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLPointCollection.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLShape.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLOpenGLStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLSource.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLPolygon.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLClockDirectionFormatter.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLFillStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLCoordinateFormatter.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLShapeOfflineRegion.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLNetworkConfiguration.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLOverlay.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLPolyline.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLLineStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLDistanceFormatter.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLHeatmapStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLOfflineRegion.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLTilePyramidOfflineRegion.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/NSValue+MGLAdditions.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLCluster.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLFeature.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLGeometry.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLAccountManager.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLTileSource.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLForegroundStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLMapCamera.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLImageSource.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLSymbolStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLCompassDirectionFormatter.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLRasterTileSource.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLVectorStyleLayer.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLShapeSource.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLLight.h
    ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLStyle.h
)

if(IOS)
    list(APPEND DARWIN_SRC
        ${PROJECT_SOURCE_DIR}/platform/darwin/src/MGLLocationManager.m
    )
endif()
